add minor bump

diff --git a/versioning/create-major-release b/versioning/create-major-release
--- a/versioning/create-major-release
+++ b/versioning/create-major-release
@@ -13,9 +13,10 @@ usage() {
     echo "USAGE: create-major-release [OPTIONS]"
     echo ""
     echo "OPTIONS:"
-    echo "  -h      print this message and exit"
-    echo "  -f      do not prompt for confirmation"
-    echo "  -n      do not fetch tags from Git remote"
+    echo "  -h        print this message and exit"
+    echo "  -f        do not prompt for confirmation"
+    echo "  -n        do not fetch tags from Git remote"
+    echo "  -b bump   version bump (major/minor)"
     echo ""
     echo "RETURNS:"
     echo "  0     success"
@@ -25,14 +26,18 @@ usage() {
 
 skip_confirmation=""
 skip_tags_fetch=""
+version_bump=""
 
-while getopts "fhn" arg; do
+while getopts "fhnb:" arg; do
   case "${arg}" in
     f)
       skip_confirmation="TRUE"
       ;;
     n)
       skip_tags_fetch="TRUE"
+      ;;
+    b)
+      version_bump=$OPTARG
       ;;
     h)
       usage
@@ -41,6 +46,10 @@ while getopts "fhn" arg; do
 done
 
 shift $((OPTIND-1))
+
+if [[ $version_bump != "major" &&  $version_bump != "minor" ]]; then
+  errexit "invalid release type - use -bmajor/minor"
+fi
 
 result=0
 
@@ -59,7 +68,8 @@ r=$?
 if [ "$r" -ne 0 ]; then
   errexit "\"git status\" failed with return code $r"
 elif [ ! -z "$git_status" ]; then
-  errexit "uncommitted changes present"
+  echo $git_status
+  errexit "uncommitted changes or untracked files present"
 fi
 
 if [ "$skip_tags_fetch" = "TRUE" ]; then
@@ -73,28 +83,63 @@ else
   fi
 fi
 
+# Uses $version_bump
+function get_new_version()
+{
+  CUR_MAJ=0
+  CUR_MIN=0
+  CUR_PATCH=0
+
+  tags=$(git tag)
+  #echo $tags
+
+  for tag in $tags
+  do
+    #echo tag: $tag
+    MAJ=$(echo $tag | awk '/^v(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)(-rc[1-9][0-9]*)?$/ {split(substr($1, 2, length($1)-1), a, "\."); print a[1]}')
+    MIN=$(echo $tag | awk '/^v(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)(-rc[1-9][0-9]*)?$/ {split(substr($1, 2, length($1)-1), a, "\."); print a[2]}')
+    if [[ $MAJ != "" && $MIN != "" ]]; then
+      #echo cur: $MAJ.$MIN
+      if [[ $MAJ > $CUR_MAJ || $MAJ == $CUR_MAJ && $MIN > $CUR_MIN ]]; then
+        CUR_MAJ=$MAJ
+        CUR_MIN=$MIN
+        fi
+        #echo max: $CUR_MAJ.$CUR_MIN
+    fi
+  done
+
+  if [[ $version_bump == "major" ]]; then
+    newmaj=$(( $CUR_MAJ + 1 ))
+    version="$newmaj.0.0"
+  elif [[ $version_bump == "minor" ]]; then
+    newmin=$(( $CUR_MIN + 1 ))
+    version="$CUR_MAJ.$newmin.0"
+  fi
+  echo $version
+}
+
 # Get all git tags and filter selecting only those with the form "vX.Y.Z[-rcW]".
 # Then take the substring "X.Y.Z", break it into the components "X", "Y" and
 # "Z[-rcW]" and select only "X" (the major version number). Sort the numbers in
 # reverse order and take the first value as the last major version number.
-last_major_version=$(git tag | awk '/^v(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)(-rc[1-9][0-9]*)?$/ { split(substr($1, 2, length($1)-1), a, "\."); print a[1] }' | sort -r | head -n 1)
-r=$?
-if [ "$r" -ne 0 ]; then
-  errexit "getting last major version from tag failed"
-elif [ -z "$last_major_version" ]; then
-  echo "No previous major version found, deafulting to 1"
-  next_major_version="1"
-else
-  echo "Last major version found: $last_major_version"
-  next_major_version=$(expr "$last_major_version" '+' '1')
-  r=$?
-  if [ "$r" -ne 0 ]; then
-    errexit "major version number increment failed with return code $r"
-  fi
-fi
+# last_major_version=$(git tag | awk '/^v(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)(-rc[1-9][0-9]*)?$/ { split(substr($1, 2, length($1)-1), a, "\."); print a[1] }' | sort -r | head -n 1)
+# r=$?
+# if [ "$r" -ne 0 ]; then
+#   errexit "getting last major version from tag failed"
+# elif [ -z "$last_major_version" ]; then
+#   echo "No previous major version found, defaulting to 1"
+#   next_major_version="1"
+# else
+#   echo "Last major version found: $last_major_version"
+#   next_major_version=$(expr "$last_major_version" '+' '1')
+#   r=$?
+#   if [ "$r" -ne 0 ]; then
+#     errexit "major version number increment failed with return code $r"
+#   fi
+# fi
 
-version="$next_major_version.0.0"
-release_branch="release-$next_major_version.0"
+version=$(get_new_version)
+release_branch="release-$version"
 release_tag="v$version"
 
 echo "Changes to be made:"
